language: node_js
node_js:
  - "v12.9.1"
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "npm i"
  - ./scripts/sync.sh
script:
  - "npm run test"
  - "npm run build --prefix-paths"

