name: Gatsby Publish

on:
  push:
    branches:
      - master
  schedule:
      - cron:  0 0 * * 0


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./scripts/sync.sh
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}