name: Build and Publish

on:
  push:
    branches:
      - master
  schedule:
      # every week
      - cron:  0 0 * * 0


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: ./scripts/sync.sh
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths